---
- name: Playbook para instalar Podman y configurar Tomcat en CentOS
  hosts: centos
  become: yes
  tasks:

    - name: Instalar Podman (DNF Backend)
      dnf:
        name: podman
        state: present

    - name: Crear directorio para almacenar archivos
      file:
        path: /temporal/contenedor
        state: directory
        owner: soporte
        group: soporte
        mode: '0777'

    - name: Copiar archivo todo.war
      copy:
        src: /home/soporte/playbooks/todo.war
        dest: /temporal/contenedor/todo.war
        owner: soporte
        group: soporte
        mode: '0777'

    - name: Copiar archivo app.properties
      copy:
        src: /home/soporte/playbooks/app.properties  
        dest: /temporal/contenedor/app.properties
        owner: soporte
        group: soporte
        mode: '0777'
        
    - name: Configurar permisos de archivos
      file:
        path: /temporal/contenedor
        state: directory
        recurse: yes
        mode: '0777'
        owner: soporte
        group: soporte

    - name: Configurar permisos de archivos en /temporal/contenedor
      file:
        path: /temporal/contenedor/todo.war
        state: file
        mode: '0777'
        owner: soporte
        group: soporte

    - name: Configurar permisos de archivo app.properties
      file:
        path: /temporal/contenedor/app.properties
        state: file
        mode: '0777'
        owner: soporte
        group: soporte

    - name: Crear archivo de servicio para Podman
      copy:
        dest: /etc/systemd/system/miservicio.service
        content: |
          [Unit]
          Description=Servicio para ejecutar Tomcat con Podman
          After=network.target

          [Service]
          Type=simple
          ExecStart=/usr/bin/podman run --rm -p 7070:8080 \
            -v /temporal/contenedor/todo.war:/usr/local/tomcat/webapps/todo.war:Z \
            -v /temporal/contenedor/app.properties:/opt/config/app.properties:Z \
            docker.io/library/tomcat:9.0
          ExecStop=/usr/bin/podman stop -t 2 tomcat-container
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target

    - name: Recargar configuración de systemd
      systemd:
        daemon_reload: yes

    - name: Habilitar y reiniciar el servicio miservicio
      systemd:
        name: miservicio.service
        enabled: yes
        state: restarted
