---
- name: Instalacion de Podman
  hosts: centos
  become: yes
  tasks:
    - name: Instalar el paquete Podman
      ansible.builtin.yum:
        name: podman
        state: present

    - name: Instalar herramientas adicionales para Podman (opcional)
      yum:
        name:
          - podman-docker
          - skopeo
        state: present

    - name: Verificar la versión instalada
      command: podman --version
      register: podman_version

    - name: Iniciar el servicio Podman
      systemd:
       name: podman.socket
       state: started
       enabled: yes

    - name: Verificar el estado del servicio Podman
      command: systemctl is-active podman
      register: podman_status
      ignore_errors: yes

    - name: Habilitar y arrancar el servicio Podman
      systemd:
        name: podman
        enabled: yes
        state: started
      when: podman_status.stdout != 'active'

    - name: Mostrar la versión instalada
      ansible.builtin.debug:
        msg: "La versión de Podman es: {{ podman_version.stdout }}"
...